### ISSUE TITLE
) at the end of a link is interpreted as part of it

### ISSUE THREAD

**Issue by MarcusMoeller** [opensource-challenge/opensource-challenge-client#11]
![bildschirmfoto_2016-12-01_12-29-20](https://cloud.githubusercontent.com/assets/1267594/20792401/d5580124-b7c1-11e6-8ac7-7ec903d62290.png)
It seems as if closing curved brackets are interpreted as part of the link.

**Comment by topaxi** [comment]
Parens are valid in URLs. The post should've used Markdown for the Link instead of relying on the auto-link behaviour.

Example: `[https://github.com/schtibe/postcardy/issues/1](https://github.com/schtibe/postcardy/issues/1)`
Example of an URL with parens: https://en.wikipedia.org/wiki/Pennywise_(band)

I'll probably have to fix this in the DB or implement the edit post functionality mentioned in #3.
